### ISSUE TITLE
The License does not look normal.

### ISSUE THREAD

**Issue by Sanye217** [ensdomains/ens-app-v3#236]
Greetings from [Water3](https://github.com/water3dao) team. I am not an expert in Korea, but is there a typo?

https://github.com/ensdomains/ens-app-v3/blob/dev/LICENSE#L3

<img width="500" alt="ens-license-screenshot" src="https://user-images.githubusercontent.com/28680496/203881558-07f4f770-572d-4650-9cd6-46c609077451.png">

**Comment by LeonmanRolls** [comment]
#252
