### ISSUE TITLE
Domain Name Transfer is Counterintuitive

### ISSUE THREAD

**Issue by Miz009** [ensdomains/ens-app-v3#237]
When transferring a domain name to someone, they will not see it in their "Names" tap but rather have to search for the domain name.

Here are the current steps:

1. Address A buys domain name 
2. Sends domain name to Address B
3. Address B has to use the ENS search function to find the name, as it does not show up in the "Name" tab
4. Address B has to change the address associated with the domain and set to "Primary Name"
5. Address B does not see the name in the "Name" tab 
6. Address A still sees the domain in their "Name" tab, but is not the controller or Owner.

Better flow:
1. Address A buys domain name 
2. Sends domain name to Address B
3. Address B sees the new domain name in their "Name" tabs and can set / modify
4. Address A does not see the transfered domain name in their "Name" tab anymore.

**Comment by LeonmanRolls** [comment]
Thanks for reporting this, can confirm this is a bug, will fix!
