### ISSUE TITLE
DNS Record Invalid (DNSSEC)

### ISSUE THREAD

**Issue by Miz009** [ensdomains/ens-app-v3#238]
Specs: 

TLD Name Provider: Namecheap 
TLD: .com domain

After enabling DNSSEC, it takes 20-30 min to be recognized by the app. 
The next step is to create a TXT record. However, it seems that the app is not recognizing it, even after waiting 24h.

<img width="709" alt="Screenshot" src="https://user-images.githubusercontent.com/104794660/204073313-38ac3755-d975-4c3b-a552-4292f626370f.png">

<img width="1164" alt="Screenshot" src="https://user-images.githubusercontent.com/104794660/204073317-d6d70a7a-f5d7-44bc-a60e-c300a4909bec.png">

**Comment by LeonmanRolls** [comment]
The value was wrong, this has been fixed now: 
<img width="676" alt="image" src="https://user-images.githubusercontent.com/1221151/230863599-d5b95412-f704-43ba-ac5b-15c29e117889.png">
