### ISSUE TITLE
"Your web3 username" section appears to have overflow clipping issues

### ISSUE THREAD

**Issue by lucemans** [ensdomains/ens-app-v3#240]
![image](https://user-images.githubusercontent.com/10339043/204110939-822fab74-74f9-4aac-bb0e-42d89d076aee.png)

**Comment by lucemans** [comment]
See the `g` in `gebruikersnaam`

**Comment by LeonmanRolls** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1221151/230861484-ad1492b0-a69e-4c31-a827-3df4f5d9dca1.png">
