### ISSUE TITLE
IPNS Record for Website is not accepted in V3

### ISSUE THREAD

**Issue by livid** [ensdomains/ens-app-v3#247]
<img width="1039" alt="Screenshot 2022-12-01 at 1 55 00 AM" src="https://user-images.githubusercontent.com/11427/205022881-c79496ad-6132-46e2-bddd-35e3b241b812.png">

It works in the previous version. For example, our website is powered with an IPNS record:

https://planetable.eth.limo

<img width="1473" alt="Screenshot 2022-12-01 at 1 57 27 AM" src="https://user-images.githubusercontent.com/11427/205023212-6dc55c41-1f85-4dce-8160-b6bfa8964470.png">

**Comment by livid** [comment]
Other dWeb projects like Nimi are also relying on IPNS.

**Comment by LeonmanRolls** [comment]
Thanks for reporting, will fix!

**Comment by storywithoutend** [comment]
Hey @livid, I'm working on the fix. I'm getting clarification on a couple details and should have the fix in soon.

A quick overview of the bug is that we are using the same validators as v2 but need to add a check for both ipfs and ipns. Appreciate you taking the time to report.
