### ISSUE TITLE
dev error

### ISSUE THREAD

**Issue by ancjf** [ensdomains/ens-app-v3#307]
I tried running ens-app-v3

Run this command:
pnpm install
pnpm dev

error occurred:
> ens-app-v2@0.1.123 dev C:\src\nodejs\ens-app-v3
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\src\nodejs\ens-app-v3\.env
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

wait  - compiling...
error - ./node_modules/.pnpm/@wagmi+core@0.5.8_6o7qlqixt7rvy6p5to6xkpdm2u/node_modules/@wagmi/core/connectors/coinbaseWallet/dist/wagmi-core-connectors-coinbaseWallet.esm.js
Error: Could not find module for providers
    at String.replace (<anonymous>)

Revision: b534b7bad2dcddb324c7afddb18d1513c8319b7b
node: v16.19.0
system: windows 11

**Comment by LeonmanRolls** [comment]
Hi are you still getting this error?
