### ISSUE TITLE
Discontiguous Upgrade Procedure

### ISSUE THREAD

**Issue by sshmatrix** [ensdomains/ens-app-v3#410]
'Upgrade' feature consisting of two steps in not contiguous and cookie-dependent. If cookies are cleared/lost between step 1 (migrate profile) & step 2 (wrap name), user has to restart from scratch and pay for step 1 again (~ 41000 gas units). This can be reproduced with any name. 

Example steps to recreate this on any name:

1) Transaction 1 (Migrate): [0x8cf5a6c070c7cf0a157dcd5150162ffe15ada49a5f5cf70226b774a36772ba9d](https://goerli.etherscan.io/tx/0x8cf5a6c070c7cf0a157dcd5150162ffe15ada49a5f5cf70226b774a36772ba9d)

2) Clear cookies or restart browser

3) Transaction 2 (Migrate again):
[0xfea15b8d1b04e12b59e1d72c7561c99e1e945aa42894341b669da6cebdb3972e](https://goerli.etherscan.io/tx/0xfea15b8d1b04e12b59e1d72c7561c99e1e945aa42894341b669da6cebdb3972e)

4) Clear cookies or restart browser again

5) Transaction 3 (Migrate again x2):
[0x5aada297e79d093978c0a9b7d0c01d3d530ae7f7cb26373907d984590dd0b1f6](https://goerli.etherscan.io/tx/0x5aada297e79d093978c0a9b7d0c01d3d530ae7f7cb26373907d984590dd0b1f6)

- Do not clear cookies after this step

6) Transaction 4 (Wrap):
[0x089886bdc95c95a27a8a0db46c2c8cf61f7f02fcb00fb1a9fb1e59e640c9a038](https://goerli.etherscan.io/tx/0x089886bdc95c95a27a8a0db46c2c8cf61f7f02fcb00fb1a9fb1e59e640c9a038)

UI shouldn't need cookies and should be able to check on-chain if step 1 has already been completed by a name before allowing step 2. UI even sends a prompt that user can leave the page and return to complete the process. This is highly misleading and doesn't mention that the user shouldn't close the browser.

**Comment by LeonmanRolls** [comment]
Thanks for reporting. You are right we can check if the resolver we are migrating to already has the same records as the current resolver. Will update when the fix is live.

**Comment by sshmatrix** [comment]
`sshmatrix.eth` when the time comes 😇

**Comment by LeonmanRolls** [comment]
Unfortunately the bug bash isn't running anymore.

**Comment by sshmatrix** [comment]
That's a shame. Less incentive to report stuff next time
