### ISSUE TITLE
Connect Wallet (Metamask) not working in Firefox

### ISSUE THREAD

**Issue by cairoeth** [ensdomains/ens-app-v3#504]
When trying to connect a wallet with Firefox, the app doesn't detect the Metamask extension installed in the browser. Therefore, it redirects the user to scan the QR code. Works as expected with Chrome.

<img width="1468" alt="image" src="https://github.com/ensdomains/ens-app-v3/assets/101215230/ecd2cd7d-2ad8-4298-9e05-538ade04c37f">

On a similar note, the button to "Add to Firefox" in the Get Metamask modal redirects the user to the Chrome store instead of the Firefox addons page.

![d00de62688bb92a392eb5834d0a08811](https://github.com/ensdomains/ens-app-v3/assets/101215230/cd27e742-2d82-4c58-952b-14a959feeefc)

**Comment by hashfriend** [comment]
worth noting this works flawlessly with rainbowkit out of the box so not clear why such a convoluted soution is needed in #501 for this app

**Comment by TateB** [comment]
> worth noting this works flawlessly with [rainbowkit](https://www.rainbowkit.com/) out of the box so not clear why such a convoluted soution is needed in #501 for this app

we have CSP headers enabled on the app site, which breaks the injection mechanism used by metamask (and other wallets) in firefox/ios

**Comment by LeonmanRolls** [comment]
You should ask firefox why they haven't fixed a years old security issue

**Comment by LeonmanRolls** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1267027

**Comment by LeonmanRolls** [comment]
It's not that we didn't perform testing, it's more a question of wanting to protect users. 

1. We could have not implemented a CSP for everyone until we figured out this issue, giving everyone a less secure experience
2. We could have not implemented a CSP for firefox/metmask users only, giving them a less secure experience. 

So the decision was to taken to not allow firefox/metamask use on the app as it is less secure only while we look for a workaround, point taken we could have done something in the UI about that in the meantime. As you can imagine implementing things in the UI for specific wallet/browser combos is a bit of a rabbit hole.

**Comment by TateB** [comment]
fix is now merged and in place

**Comment by 5ajaki** [comment]
@TateB or @LeonmanRolls - Is this CSP implementation what's preventing the injected provider option ("Browser Wallet") from showing in the Rainbowkit Modal when using Firefox?

<img width="1381" alt="RainbowKit" src="https://github.com/ensdomains/ens-app-v3/assets/125100304/036e127f-7b61-4563-a24f-ab9e7bb6e817">

**Comment by TateB** [comment]
iirc "Browser Wallet" isn't an option on the rainbowkit version the main build is on, unrelated to CSP.

**Comment by 5ajaki** [comment]
The current site seems to disagree.  Screen shot from now.

<img width="1060" alt="image" src="https://github.com/ensdomains/ens-app-v3/assets/125100304/54455320-f7d7-4721-bad9-05f6f1e62276">

I see you're calling the Injected Wallet option in the config of the current build, perhaps that's where this is coming from?

**Comment by TateB** [comment]
just to clarify, what wallet are you trying to use with firefox?

**Comment by 5ajaki** [comment]
Frame.sh

**Comment by 5ajaki** [comment]
@TateB - any thoughts?  Are we back to first question of “is it our CSP implementation that’s preventing the “Browser Wallet” option from showing in Firefox while in Brave it does?

**Comment by TateB** [comment]
sorry, yep this would be the CSP on the site. we need to manually inject a metamask provider loader for firefox user agents. we need to specify and add every injected provider that we want to load in firefox unfortunately. 

afaik there's no good solution for this issue (other than firefox fixing it), but i'm open to ideas.
