### ISSUE TITLE
Discord button doesn't copy username

### ISSUE THREAD

**Issue by octal-crypto** [ensdomains/ens-app-v3#550]
On the profile page, the Discord button has a copy icon.  But clicking it does not copy the username, like it does for other copy buttons on the page.

See:
- https://app.ens.domains/nick.eth
- https://app.ens.domains/octal.eth

<img width="629" alt="Screenshot 2023-07-17 at 4 17 27 PM" src="https://github.com/ensdomains/ens-app-v3/assets/95519094/9a83c89f-3cae-4124-ad8b-8b15ef8d9752">

**Comment by Trees0x** [comment]
@octal-crypto this commit should resolve the issue: https://github.com/ensdomains/ens-app-v3/pull/555

**Comment by LeonmanRolls** [comment]
Fixed in #561
