### ISSUE TITLE
CCIP-read and wildcard is not supported

### ISSUE THREAD

**Issue by makoto** [ensdomains/ens-app-v3#58]
- https://alpha.ens.domains/profile/1.offchainexample.eth
and https://alpha.ens.domains/profile/offchainexample.eth should show the same record as https://app.ens.domains/name/offchainexample.eth/details and https://app.ens.domains/name/1.offchainexample.eth 
- Also please show `This domain may have other subdomains that cannot be shown as they are off chain` at the subnames page.
- Please refer to https://github.com/ensdomains/ens-app/pull/1468 for how I implemented.
- Please also use `ethereum-provider` 1.8.0-rc.0` for walletconnect that supports CCIP read. Reference https://github.com/ensdomains/ens-app/pull/1526/files

**Comment by LeonmanRolls** [comment]
pending batched universal resolver
