### ISSUE TITLE
NFT avatar not showing on ENS profile

### ISSUE THREAD

**Issue by rex4539** [ensdomains/ens-app-v3#918]
I have set up my ENS NFT as my avatar but it's not showing on my profile.

https://app.ens.domains/dimitrisapostolou.eth

**Comment by mdtanrikulu** [comment]
hey @rex4539, NFTs that don't fully comply with the erc721/1155 standards will not work as avatars, e.g. CryptoKitties, or In your case, the NameWrapper contract does not provide a tokenURI for the metadata.
